# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Source Options
# Use Modern Java(9+) Syntax (Courtesy of Jabel)
use_modern_java_syntax = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

mod_version=0.5.6
root_package=zmaster587.libVulpes
mod_id=libvulpes
mod_name=LibVulpes

mod_description=A library containing code for multiblocks and ore/item registration and access.
mod_authors=zmaster587
mod_credits=
mod_url=
mod_update_json=
mod_logo_path=

minecraft_username=Developer
jeiVersion=4.16.1.301

# start with the same mapping style your AR repo expects
mapping_channel = snapshot
mapping_version = 20171003


use_tags=true
tag_class_name=zmaster587.libVulpes.Tags

use_access_transformer=false
access_transformer_locations=META-INF/libvulpes_at.cfg

use_mixins=false
mixin_booter_version=
mixin_refmap=mixins.libvulpes.refmap.json
mixin_package=
mixin_configs=

is_coremod=false
coremod_includes_mod=false
coremod_plugin_class_name=

use_asset_mover=false
asset_mover_version=

use_dependency_at_files=true
extra_jvm_args=
extra_tweak_classes=
change_minecraft_sources=false

publish_to_maven=false
publish_to_curseforge=false
publish_to_modrinth=false